// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dispatch_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdateDispatchConfig = `-- name: BatchUpdateDispatchConfig :exec
UPDATE dispatch_config
SET 
    value = updates.value,
    updated_at = NOW()
FROM (
    SELECT unnest($1::text[]) AS key, unnest($2::numeric[]) AS value
) AS updates
WHERE dispatch_config.key = updates.key
`

type BatchUpdateDispatchConfigParams struct {
	Column1 []string         `json:"column_1"`
	Column2 []pgtype.Numeric `json:"column_2"`
}

func (q *Queries) BatchUpdateDispatchConfig(ctx context.Context, arg BatchUpdateDispatchConfigParams) error {
	_, err := q.db.Exec(ctx, batchUpdateDispatchConfig, arg.Column1, arg.Column2)
	return err
}

const getBaseMinReserve = `-- name: GetBaseMinReserve :one
SELECT COALESCE(value, 1)::int AS minReserve
FROM dispatch_config
WHERE key = 'min_reserve_per_base'
`

func (q *Queries) GetBaseMinReserve(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getBaseMinReserve)
	var minreserve int32
	err := row.Scan(&minreserve)
	return minreserve, err
}

const getDispatchConfigValue = `-- name: GetDispatchConfigValue :one
SELECT 
    key, 
    value, 
    description, 
    min_value, 
    max_value, 
    updated_at
FROM dispatch_config
WHERE key = $1
`

func (q *Queries) GetDispatchConfigValue(ctx context.Context, key string) (DispatchConfig, error) {
	row := q.db.QueryRow(ctx, getDispatchConfigValue, key)
	var i DispatchConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.MinValue,
		&i.MaxValue,
		&i.UpdatedAt,
	)
	return i, err
}

const listBases = `-- name: ListBases :many

SELECT DISTINCT 
    home_base AS name,
    COUNT(*) FILTER (WHERE status = 'available') AS available_units,
    COUNT(*) AS total_units
FROM units
WHERE home_base IS NOT NULL AND home_base != ''
GROUP BY home_base
ORDER BY home_base
`

type ListBasesRow struct {
	Name           *string `json:"name"`
	AvailableUnits int64   `json:"available_units"`
	TotalUnits     int64   `json:"total_units"`
}

// =============================================================================
// Static Data Queries (for engine startup)
// =============================================================================
func (q *Queries) ListBases(ctx context.Context) ([]ListBasesRow, error) {
	rows, err := q.db.Query(ctx, listBases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBasesRow
	for rows.Next() {
		var i ListBasesRow
		if err := rows.Scan(&i.Name, &i.AvailableUnits, &i.TotalUnits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispatchConfig = `-- name: ListDispatchConfig :many

SELECT 
    key, 
    value, 
    description, 
    min_value, 
    max_value, 
    updated_at
FROM dispatch_config
ORDER BY key
`

// =============================================================================
// Dispatch Configuration Queries
// =============================================================================
func (q *Queries) ListDispatchConfig(ctx context.Context) ([]DispatchConfig, error) {
	rows, err := q.db.Query(ctx, listDispatchConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DispatchConfig
	for rows.Next() {
		var i DispatchConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.MinValue,
			&i.MaxValue,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDispatchConfigValue = `-- name: UpdateDispatchConfigValue :one
UPDATE dispatch_config
SET 
    value = $2,
    updated_at = NOW()
WHERE key = $1
RETURNING key, value, description, min_value, max_value, updated_at
`

type UpdateDispatchConfigValueParams struct {
	Key   string         `json:"key"`
	Value pgtype.Numeric `json:"value"`
}

func (q *Queries) UpdateDispatchConfigValue(ctx context.Context, arg UpdateDispatchConfigValueParams) (DispatchConfig, error) {
	row := q.db.QueryRow(ctx, updateDispatchConfigValue, arg.Key, arg.Value)
	var i DispatchConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.MinValue,
		&i.MaxValue,
		&i.UpdatedAt,
	)
	return i, err
}
