// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssignmentStatus string

const (
	AssignmentStatusDispatched AssignmentStatus = "dispatched"
	AssignmentStatusArrived    AssignmentStatus = "arrived"
	AssignmentStatusReleased   AssignmentStatus = "released"
	AssignmentStatusCancelled  AssignmentStatus = "cancelled"
)

func (e *AssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentStatus(s)
	case string:
		*e = AssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentStatus: %T", src)
	}
	return nil
}

type NullAssignmentStatus struct {
	AssignmentStatus AssignmentStatus `json:"assignment_status"`
	Valid            bool             `json:"valid"` // Valid is true if AssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentStatus), nil
}

type DecisionMode string

const (
	DecisionModeAutoSuggested DecisionMode = "auto_suggested"
	DecisionModeManual        DecisionMode = "manual"
)

func (e *DecisionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DecisionMode(s)
	case string:
		*e = DecisionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for DecisionMode: %T", src)
	}
	return nil
}

type NullDecisionMode struct {
	DecisionMode DecisionMode `json:"decision_mode"`
	Valid        bool         `json:"valid"` // Valid is true if DecisionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDecisionMode) Scan(value interface{}) error {
	if value == nil {
		ns.DecisionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DecisionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDecisionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DecisionMode), nil
}

type InterventionStatus string

const (
	InterventionStatusCreated   InterventionStatus = "created"
	InterventionStatusOnSite    InterventionStatus = "on_site"
	InterventionStatusCompleted InterventionStatus = "completed"
	InterventionStatusCancelled InterventionStatus = "cancelled"
)

func (e *InterventionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InterventionStatus(s)
	case string:
		*e = InterventionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InterventionStatus: %T", src)
	}
	return nil
}

type NullInterventionStatus struct {
	InterventionStatus InterventionStatus `json:"intervention_status"`
	Valid              bool               `json:"valid"` // Valid is true if InterventionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInterventionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InterventionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InterventionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInterventionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InterventionStatus), nil
}

type UnitStatus string

const (
	UnitStatusAvailable   UnitStatus = "available"
	UnitStatusUnderWay    UnitStatus = "under_way"
	UnitStatusOnSite      UnitStatus = "on_site"
	UnitStatusUnavailable UnitStatus = "unavailable"
	UnitStatusOffline     UnitStatus = "offline"
)

func (e *UnitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitStatus(s)
	case string:
		*e = UnitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitStatus: %T", src)
	}
	return nil
}

type NullUnitStatus struct {
	UnitStatus UnitStatus `json:"unit_status"`
	Valid      bool       `json:"valid"` // Valid is true if UnitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UnitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitStatus), nil
}

type Event struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	ReportSource  *string            `json:"report_source"`
	Address       *string            `json:"address"`
	Location      interface{}        `json:"location"`
	Severity      int32              `json:"severity"`
	EventTypeCode string             `json:"event_type_code"`
	ReportedAt    pgtype.Timestamptz `json:"reported_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
}

type EventLog struct {
	ID        int64              `json:"id"`
	EventID   pgtype.UUID        `json:"event_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Code      string             `json:"code"`
	Actor     *string            `json:"actor"`
	Payload   []byte             `json:"payload"`
}

type EventType struct {
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	Description          string             `json:"description"`
	DefaultSeverity      int32              `json:"default_severity"`
	RecommendedUnitTypes []string           `json:"recommended_unit_types"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Intervention struct {
	ID           pgtype.UUID        `json:"id"`
	EventID      pgtype.UUID        `json:"event_id"`
	Status       InterventionStatus `json:"status"`
	Priority     int32              `json:"priority"`
	DecisionMode DecisionMode       `json:"decision_mode"`
	CreatedBy    *string            `json:"created_by"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type InterventionAssignment struct {
	ID             pgtype.UUID        `json:"id"`
	InterventionID pgtype.UUID        `json:"intervention_id"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	Role           *string            `json:"role"`
	Status         AssignmentStatus   `json:"status"`
	DispatchedAt   pgtype.Timestamptz `json:"dispatched_at"`
	ArrivedAt      pgtype.Timestamptz `json:"arrived_at"`
	ReleasedAt     pgtype.Timestamptz `json:"released_at"`
}

type InterventionCrew struct {
	ID             pgtype.UUID        `json:"id"`
	InterventionID pgtype.UUID        `json:"intervention_id"`
	PersonnelID    pgtype.UUID        `json:"personnel_id"`
	Role           *string            `json:"role"`
	Status         string             `json:"status"`
	AssignedAt     pgtype.Timestamptz `json:"assigned_at"`
	ReleasedAt     pgtype.Timestamptz `json:"released_at"`
}

type Personnel struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	Rank      *string            `json:"rank"`
	Status    string             `json:"status"`
	HomeBase  *string            `json:"home_base"`
	Contact   *string            `json:"contact"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Unit struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	Location      interface{}        `json:"location"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MicrobitID    *string            `json:"microbit_id"`
}

type UnitTelemetry struct {
	ID             int64              `json:"id"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	Location       interface{}        `json:"location"`
	Heading        *int32             `json:"heading"`
	SpeedKmh       *float64           `json:"speed_kmh"`
	StatusSnapshot []byte             `json:"status_snapshot"`
}

type UnitType struct {
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	Capabilities string             `json:"capabilities"`
	SpeedKmh     *int32             `json:"speed_kmh"`
	MaxCrew      *int32             `json:"max_crew"`
	Illustration *string            `json:"illustration"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
