// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: types.sql

package db

import (
	"context"
)

const listEventTypes = `-- name: ListEventTypes :many
SELECT
    code,
    name,
    description,
    default_severity,
    recommended_unit_types,
    created_at,
    updated_at
FROM event_types
ORDER BY default_severity DESC, name
`

func (q *Queries) ListEventTypes(ctx context.Context) ([]EventType, error) {
	rows, err := q.db.Query(ctx, listEventTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventType
	for rows.Next() {
		var i EventType
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DefaultSeverity,
			&i.RecommendedUnitTypes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitTypes = `-- name: ListUnitTypes :many
SELECT
    code,
    name,
    capabilities,
    speed_kmh,
    max_crew,
    illustration,
    created_at,
    updated_at
FROM unit_types
ORDER BY name
`

func (q *Queries) ListUnitTypes(ctx context.Context) ([]UnitType, error) {
	rows, err := q.db.Query(ctx, listUnitTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UnitType
	for rows.Next() {
		var i UnitType
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Capabilities,
			&i.SpeedKmh,
			&i.MaxCrew,
			&i.Illustration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
