// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignMicrobit = `-- name: AssignMicrobit :one
UPDATE units
SET
    microbit_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
`

type AssignMicrobitParams struct {
	ID         pgtype.UUID `json:"id"`
	MicrobitID *string     `json:"microbit_id"`
}

type AssignMicrobitRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) AssignMicrobit(ctx context.Context, arg AssignMicrobitParams) (AssignMicrobitRow, error) {
	row := q.db.QueryRow(ctx, assignMicrobit, arg.ID, arg.MicrobitID)
	var i AssignMicrobitRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (
    call_sign,
    unit_type_code,
    home_base,
    status,
    location,
    last_contact_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    ST_SetSRID(
        ST_MakePoint(
            $5::double precision,
            $6::double precision
        ),
        4326
    )::geography,
    $7
) RETURNING
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
`

type CreateUnitParams struct {
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
}

type CreateUnitRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (CreateUnitRow, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.CallSign,
		arg.UnitTypeCode,
		arg.HomeBase,
		arg.Status,
		arg.Longitude,
		arg.Latitude,
		arg.LastContactAt,
	)
	var i CreateUnitRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :exec
DELETE FROM units WHERE id = $1
`

func (q *Queries) DeleteUnit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnit, id)
	return err
}

const deleteUnitAssignments = `-- name: DeleteUnitAssignments :exec
DELETE FROM intervention_assignments WHERE unit_id = $1
`

func (q *Queries) DeleteUnitAssignments(ctx context.Context, unitID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnitAssignments, unitID)
	return err
}

const deleteUnitTelemetry = `-- name: DeleteUnitTelemetry :exec
DELETE FROM unit_telemetry WHERE unit_id = $1
`

func (q *Queries) DeleteUnitTelemetry(ctx context.Context, unitID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnitTelemetry, unitID)
	return err
}

const getUnit = `-- name: GetUnit :one
SELECT
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
FROM units
WHERE id = $1
`

type GetUnitRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUnit(ctx context.Context, id pgtype.UUID) (GetUnitRow, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i GetUnitRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitByMicrobitID = `-- name: GetUnitByMicrobitID :one
SELECT
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
FROM units
WHERE microbit_id = $1
`

type GetUnitByMicrobitIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUnitByMicrobitID(ctx context.Context, microbitID *string) (GetUnitByMicrobitIDRow, error) {
	row := q.db.QueryRow(ctx, getUnitByMicrobitID, microbitID)
	var i GetUnitByMicrobitIDRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUnitTelemetry = `-- name: InsertUnitTelemetry :one
INSERT INTO unit_telemetry (
    unit_id,
    location,
    heading,
    speed_kmh,
    status_snapshot
) VALUES (
    $1,
    ST_SetSRID(
        ST_MakePoint(
            $2::double precision,
            $3::double precision
        ),
        4326
    )::geography,
    $4,
    $5,
    $6
) RETURNING
    id,
    unit_id,
    recorded_at,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    heading,
    speed_kmh,
    status_snapshot
`

type InsertUnitTelemetryParams struct {
	UnitID         pgtype.UUID `json:"unit_id"`
	Longitude      float64     `json:"longitude"`
	Latitude       float64     `json:"latitude"`
	Heading        *int32      `json:"heading"`
	SpeedKmh       *float64    `json:"speed_kmh"`
	StatusSnapshot []byte      `json:"status_snapshot"`
}

type InsertUnitTelemetryRow struct {
	ID             int64              `json:"id"`
	UnitID         pgtype.UUID        `json:"unit_id"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	Longitude      float64            `json:"longitude"`
	Latitude       float64            `json:"latitude"`
	Heading        *int32             `json:"heading"`
	SpeedKmh       *float64           `json:"speed_kmh"`
	StatusSnapshot []byte             `json:"status_snapshot"`
}

func (q *Queries) InsertUnitTelemetry(ctx context.Context, arg InsertUnitTelemetryParams) (InsertUnitTelemetryRow, error) {
	row := q.db.QueryRow(ctx, insertUnitTelemetry,
		arg.UnitID,
		arg.Longitude,
		arg.Latitude,
		arg.Heading,
		arg.SpeedKmh,
		arg.StatusSnapshot,
	)
	var i InsertUnitTelemetryRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RecordedAt,
		&i.Longitude,
		&i.Latitude,
		&i.Heading,
		&i.SpeedKmh,
		&i.StatusSnapshot,
	)
	return i, err
}

const listAvailableUnitsNearby = `-- name: ListAvailableUnitsNearby :many
SELECT
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at,
    ST_Distance(location, ST_SetSRID(ST_MakePoint($1::double precision, $2::double precision), 4326)::geography)::double precision AS distance
FROM units
WHERE status = 'available'
AND ($3::text[] IS NULL OR unit_type_code = ANY($3::text[]))
ORDER BY distance ASC
`

type ListAvailableUnitsNearbyParams struct {
	Longitude float64  `json:"longitude"`
	Latitude  float64  `json:"latitude"`
	UnitTypes []string `json:"unit_types"`
}

type ListAvailableUnitsNearbyRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Distance      float64            `json:"distance"`
}

func (q *Queries) ListAvailableUnitsNearby(ctx context.Context, arg ListAvailableUnitsNearbyParams) ([]ListAvailableUnitsNearbyRow, error) {
	rows, err := q.db.Query(ctx, listAvailableUnitsNearby, arg.Longitude, arg.Latitude, arg.UnitTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableUnitsNearbyRow
	for rows.Next() {
		var i ListAvailableUnitsNearbyRow
		if err := rows.Scan(
			&i.ID,
			&i.CallSign,
			&i.UnitTypeCode,
			&i.HomeBase,
			&i.Status,
			&i.MicrobitID,
			&i.Longitude,
			&i.Latitude,
			&i.LastContactAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
FROM units
ORDER BY call_sign
`

type ListUnitsRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUnits(ctx context.Context) ([]ListUnitsRow, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitsRow
	for rows.Next() {
		var i ListUnitsRow
		if err := rows.Scan(
			&i.ID,
			&i.CallSign,
			&i.UnitTypeCode,
			&i.HomeBase,
			&i.Status,
			&i.MicrobitID,
			&i.Longitude,
			&i.Latitude,
			&i.LastContactAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignMicrobit = `-- name: UnassignMicrobit :one
UPDATE units
SET
    microbit_id = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
`

type UnassignMicrobitRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UnassignMicrobit(ctx context.Context, id pgtype.UUID) (UnassignMicrobitRow, error) {
	row := q.db.QueryRow(ctx, unassignMicrobit, id)
	var i UnassignMicrobitRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnitLocation = `-- name: UpdateUnitLocation :one
UPDATE units
SET
    location = ST_SetSRID(
        ST_MakePoint(
            $1::double precision,
            $2::double precision
        ),
        4326
    )::geography,
    last_contact_at = COALESCE($3, NOW()),
    updated_at = NOW()
WHERE id = $4
RETURNING
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
`

type UpdateUnitLocationParams struct {
	Longitude   float64            `json:"longitude"`
	Latitude    float64            `json:"latitude"`
	ContactTime pgtype.Timestamptz `json:"contact_time"`
	ID          pgtype.UUID        `json:"id"`
}

type UpdateUnitLocationRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUnitLocation(ctx context.Context, arg UpdateUnitLocationParams) (UpdateUnitLocationRow, error) {
	row := q.db.QueryRow(ctx, updateUnitLocation,
		arg.Longitude,
		arg.Latitude,
		arg.ContactTime,
		arg.ID,
	)
	var i UpdateUnitLocationRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnitLocationByMicrobitID = `-- name: UpdateUnitLocationByMicrobitID :one
UPDATE units
SET
    location = ST_SetSRID(
        ST_MakePoint(
            $1::double precision,
            $2::double precision
        ),
        4326
    )::geography,
    last_contact_at = NOW(),
    updated_at = NOW()
WHERE microbit_id = $3
RETURNING
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
`

type UpdateUnitLocationByMicrobitIDParams struct {
	Longitude  float64 `json:"longitude"`
	Latitude   float64 `json:"latitude"`
	MicrobitID *string `json:"microbit_id"`
}

type UpdateUnitLocationByMicrobitIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUnitLocationByMicrobitID(ctx context.Context, arg UpdateUnitLocationByMicrobitIDParams) (UpdateUnitLocationByMicrobitIDRow, error) {
	row := q.db.QueryRow(ctx, updateUnitLocationByMicrobitID, arg.Longitude, arg.Latitude, arg.MicrobitID)
	var i UpdateUnitLocationByMicrobitIDRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnitStatus = `-- name: UpdateUnitStatus :one
UPDATE units
SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
`

type UpdateUnitStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status UnitStatus  `json:"status"`
}

type UpdateUnitStatusRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUnitStatus(ctx context.Context, arg UpdateUnitStatusParams) (UpdateUnitStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUnitStatus, arg.ID, arg.Status)
	var i UpdateUnitStatusRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUnitStatusByMicrobitID = `-- name: UpdateUnitStatusByMicrobitID :one
UPDATE units
SET
    status = $2,
    last_contact_at = NOW(),
    updated_at = NOW()
WHERE microbit_id = $1
RETURNING
    id,
    call_sign,
    unit_type_code,
    home_base,
    status,
    microbit_id,
    (COALESCE(ST_X(location::geometry)::double precision, 0::double precision))::double precision AS longitude,
    (COALESCE(ST_Y(location::geometry)::double precision, 0::double precision))::double precision AS latitude,
    last_contact_at,
    created_at,
    updated_at
`

type UpdateUnitStatusByMicrobitIDParams struct {
	MicrobitID *string    `json:"microbit_id"`
	Status     UnitStatus `json:"status"`
}

type UpdateUnitStatusByMicrobitIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	CallSign      string             `json:"call_sign"`
	UnitTypeCode  string             `json:"unit_type_code"`
	HomeBase      *string            `json:"home_base"`
	Status        UnitStatus         `json:"status"`
	MicrobitID    *string            `json:"microbit_id"`
	Longitude     float64            `json:"longitude"`
	Latitude      float64            `json:"latitude"`
	LastContactAt pgtype.Timestamptz `json:"last_contact_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUnitStatusByMicrobitID(ctx context.Context, arg UpdateUnitStatusByMicrobitIDParams) (UpdateUnitStatusByMicrobitIDRow, error) {
	row := q.db.QueryRow(ctx, updateUnitStatusByMicrobitID, arg.MicrobitID, arg.Status)
	var i UpdateUnitStatusByMicrobitIDRow
	err := row.Scan(
		&i.ID,
		&i.CallSign,
		&i.UnitTypeCode,
		&i.HomeBase,
		&i.Status,
		&i.MicrobitID,
		&i.Longitude,
		&i.Latitude,
		&i.LastContactAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
